# Generated by Django 4.2.18 on 2025-01-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vps',
            old_name='uuid',
            new_name='uid',
        ),
    ]
