# Generated by Django 4.2.18 on 2025-01-16 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vps_app', '0002_rename_uuid_vps_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
